//引入css
require("../../css/style.css");
//引入js
require("../../js/flexible.js");
require("../../js/jquery-1.8.3.min.js");
require("../../js/common.js");
require("../../package/dropload/dropload.css");
require("../../package/dropload/dropload.min.js");
require("../../js/fastclick.js");
