new Vue({
    el:'#index',
    data:{
        header:{
            text:"中国政府管理案例库"
        },
        indexLists:[
            {
                bgUrl:"build/img/index1.png",
                text:"政务服务案例库",
                spText:"128,123篇"
            },
            {
                bgUrl:"build/img/index2.png",
                text:"政务管理案例库",
                spText:"863,59篇"
            },
            {
                bgUrl:"build/img/index3.png",
                text:"政务舆情案例库",
                spText:"128,123篇"
            },
            {
                bgUrl:"build/img/index4.png",
                text:"政府文献库",
                spText:"128,123篇"
            },
            {
                bgUrl:"build/img/index5.png",
                text:"党风廉政及反腐斗争案例库",
                spText:"128,123篇"
            },
            {
                bgUrl:"build/img/index6.png",
                text:"司法案例库",
                spText:"128,123篇"
            },
            {
                bgUrl:"build/img/index7.png",
                text:"中国公务员信息库",
                spText:"128,123篇"
            },
            {
                bgUrl:"build/img/index8.png",
                text:"政府公报库",
                spText:"128,123篇"
            },
            {
                bgUrl:"build/img/index9.png",
                text:"政情数据库",
                spText:"128,123篇"
            },
            {
                bgUrl:"build/img/index10.png",
                text:"外语案例库",
                spText:"128,123篇"
            }
        ],
        cjk_row:{
            isLogin:true,
            email:"5435755585@qq.com"
        }
    },
    methods:{
        backTop:function(){
            $('.content').scrollTop(0);
        }
    },
    mounted:function(){
        var top=$(".content").scrollTop()+window.innerHeight-100;
        $(".cjk_fixed").css("top",top+"px");
        $(".content").on('scroll',function(){
            top=$(".content").scrollTop()+window.innerHeight-100;
            $(".cjk_fixed").css("top",top+"px");
        });
    }
});
